apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: credity-issuer
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:asia-south1:credity-sql"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/credity/issuer:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: REQUIRE_DATABASE
              value: "true"
            - name: REQUIRE_QUEUE
              value: "true"
            - name: ALLOW_DEMO_ROUTES
              value: "false"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: credity-wallet
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:asia-south1:credity-sql"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/credity/wallet:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: REQUIRE_DATABASE
              value: "true"
            - name: ALLOW_DEMO_ROUTES
              value: "false"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: credity-recruiter
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:asia-south1:credity-sql"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/credity/recruiter:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: REQUIRE_DATABASE
              value: "true"
            - name: ALLOW_DEMO_ROUTES
              value: "false"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: credity-gateway
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/credity/gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
